import {
  CHILDREN_STATUS_FIELD_PROMPT_PLACEHOLDER,
  CHAT_HISTORY_FIELD_PROMPT_PLACEHOLDER,
  LAST_INPUT_FIELD_PROMPT_PLACEHOLDER,
  DYNAMIC_PROMPT_SEPARATOR,
} from '../consts';

export const BASE_DECIDER_DYNAMIC_PROMPT_TEMPLATE = `### Children status:
${CHILDREN_STATUS_FIELD_PROMPT_PLACEHOLDER}
### End of children status.

### Chat history:
${CHAT_HISTORY_FIELD_PROMPT_PLACEHOLDER}

${DYNAMIC_PROMPT_SEPARATOR}

### Last input:
${LAST_INPUT_FIELD_PROMPT_PLACEHOLDER}`;
